services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: D1ymf8wyQEGthFR1E9xhCq
      POSTGRES_USER: LTIdbUser
      POSTGRES_DB: LTIdb
    ports:
      - "5433:5432"  # Mapea el puerto 5432 del contenedor al 5433 del host
