version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: LTIdbUser
      POSTGRES_PASSWORD: D1ymf8wyQEGthFR1E9xhCq
      POSTGRES_DB: LTIdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
