version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: LTIdbUser
      POSTGRES_PASSWORD: MiPostgre2025!DB
      POSTGRES_DB: LTIdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
