version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: npg_G7YucaBWe6IL
      POSTGRES_USER: LTI_db_owner
      POSTGRES_DB: LTI_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
